// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using chipchop.Datalayer.Context;

#nullable disable

namespace chipchop.Datalayer.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240219171313_newDATABASE")]
    partial class newDATABASE
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("chipchop.Datalayer.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("RoleTitle")
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("af2b31a1-0de9-4719-b564-737f5bd2c986"),
                            RoleName = "admin",
                            RoleTitle = "مدیر"
                        });
                });

            modelBuilder.Entity("chipchop.Datalayer.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("1145f7e3-b37e-4fd1-9e2f-4a5253fbe745"),
                            IsActive = true,
                            RoleId = new Guid("af2b31a1-0de9-4719-b564-737f5bd2c986"),
                            UserName = "NoName",
                            UserPassword = "JfnnlDI7RTiF9RgfG2JNCw=="
                        });
                });

            modelBuilder.Entity("chipchop.Datalayer.Models.Role", b =>
                {
                    b.HasOne("chipchop.Datalayer.Models.Role", null)
                        .WithMany("Roles")
                        .HasForeignKey("RoleId");
                });

            modelBuilder.Entity("chipchop.Datalayer.Models.User", b =>
                {
                    b.HasOne("chipchop.Datalayer.Models.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("chipchop.Datalayer.Models.Role", b =>
                {
                    b.Navigation("Roles");
                });
#pragma warning restore 612, 618
        }
    }
}
